### ISSUE TITLE
iOS setup issue

### ISSUE THREAD

**Issue by grabcode** [evollu/react-native-firebase-analytics#21]
Hi,

Thanks for your effort. I look to using this plugin. A glitch though, whilst getting the app to build via xcode: 
`Undefined symbols for architecture`  with `"_OBJC_CLASS_$_FIRApp"`

Here is the solution:
http://stackoverflow.com/questions/37344676/undefined-symbols-for-architecture-armv7-objc-class-firapp

Cheers,
Alex

**Comment by luisfuertes** [comment]
I had the same problem, 

I already have `$(inherited)` flag on "Other Linker Flags" in Build Settings, 
but my project dont compile because "ProjectnameTest" crash with same errors your, i try to add the same flags to "Other Linker Flash", (Only had diferent `-lc++` ) and now project compile but crash on init.

Some solution?

EDIT: Ok, when i add `-lc++` i only need add `GoogleService-Info.plist` to my project and it works.

**Comment by antseburova** [comment]
This helped me:
http://stackoverflow.com/questions/19213782/undefined-symbols-for-architecture-arm64
