### ISSUE TITLE
duplicate entry: com/google/android/gms/common/api/zza.class

### ISSUE THREAD

**Issue by luisfpinto** [evollu/react-native-firebase-analytics#27]
I'm getting this error when I link the dependency:

```
Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/google/android/gms/common/api/zza.class
```

**Comment by seato** [comment]
@luisfpinto What was your solution?

**Comment by KendraTang** [comment]
@luisfpinto  I'm getting this error now, so how did you solve this?

---

Just spent some time to make things work Orz..
I found that "duplicate entry" is because I have `compile 'com.google.android.gms:play-services-auth:9.4.0'` in my dependencies.
And after I update play-services-auth to 10.0.1, problem solved.

**Comment by wasa4587** [comment]
i've tried to solve this for days, @KazooTang your sulition worked like a charm

**Comment by HITESHGOEL08** [comment]
I am having the same problem, I am using the latest version of Google play services dependencies.

**Comment by MinaSamirCap** [comment]
In my case there was a library that I used in my project.
this library also use google play services dependencies so Igot the error of duplicated entity.
///////// I solve it by adding exclude to the library like this 
compile ('com.github.ar-android:DrawRouteMaps:1.0.0'){
        transitive = true
        exclude group: 'com.google.android.gms'
    }
hope this helpful for you
